name: Unit Tests & Coverage Check

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: actions/runPVSTestAction

    steps:
      - name: Checkout test code from BruteSquad repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry install

      - name: Run Shared Unit Test Action for PVS Test
        uses: acloudgurus/shared-github-actions/test/python@master
        with:
          toml_parent_dir: "actions/runPVSTestAction"
          debug_mode: true
          environment_usage: "poetry"
          additional_args: "-v"
          coverage_gate: 80

      - name: Run Shared Unit Test Action for toml utilities
        uses: acloudgurus/shared-github-actions/test/python@master
        with:
          toml_parent_dir: "actions/findSqlFolderAction/utilities/toml_utilities"
          debug_mode: true
          environment_usage: "poetry"
          additional_args: "-v"
          coverage_gate: 80
